### ISSUE TITLE
[Bug] New Team captain not able to edit or adjust the tournament registration.

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#117]
**Describe the bug**
Assigned a new team captain with no team role but error message showing that the user isn't the captain is showing up.

**To Reproduce**
1. Create a team that has a member with no role
2. Register the team in a tournament. 
3. Include member with the no role.
4. After tournament registration, select member with no team role as new captain.
5. Using the account of the team member with the new team captain role, attempt to leave tournament or set another member as team captain.

**Expected behavior**

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://drive.google.com/file/d/1hDmJfW5L9gOoN3ktuFWQbM54TQTjysFv/view

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4cjr390b94gpyrwn5xhn40n5d8

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
Issue reported by Gosu

**Comment by JayWongjedjan** [comment]
Related issue with #112 where the tournament captain only be assigned to readying up and submitting scores for the tournament, the error that's showing means that that player is not a team manager so he cannot manage the registration because his role in that team is just a player. What needs to be done here is to give a better error message or change the message from 
_"Player is not the team captain of this team"_ to _"Player is not a team manager of this team"_

**Comment by EJNiones** [comment]
Issue still present:

https://gyazo.com/2b4c39588f3012c64a697ed45b745c1a

**Comment by AydinE** [comment]
@EJNiones please re-test

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/c3a1410378473cfa0e16ebc72182e692
