### ISSUE TITLE
[Bug] Match chat room and window is not created on a manual mode tournament

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#121]
**Describe the bug**
Tournaments that have manual mode enabled do not create a match chat room / window

**To Reproduce**
1. I am registered user already registered to a tournament
2. Tournament is using manual mode
3. Admin has manually started my match
4. On my match page, I do not see a chat window opened nor I see one on the chat menu options

**Expected behavior**
Match chat for this mode should be available when users click on their chat log.

https://gyazo.com/996615ec9777ec0903bc1e8384f74b6d

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/baeb56b86931ac475e9c7000c7ae1647

https://drive.google.com/file/d/1Os8LpxvXcUEwSr2hfzG6A0rmBfH8MLpG/view

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4j6ygg0mhzzxb3w9hktf330xx8

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
Match chat for manual mode also does not show up on the chat list:

https://gyazo.com/dd0a8cd3cb46af3247695680bb7af912

**Comment by AydinE** [comment]
This is partially as intended and has partially been fixed. The main issue is that tournaments in manual mode typically do not go through a ReadyUp stage and that's when things like chat and notifications are sent out. Skipping ready up means those things will never be triggered.

On friday I have implemented an option on the admin panel to "Start Ready Up" instead of "Start match" that should make the match go through ready up phase. If you use Start Match it will still not do chat this is only meant for pure manual tournaments where all actions are done by admin.

**Comment by EJNiones** [comment]
Confirmed implemented:

https://gyazo.com/05a637313cf9ca16809cd0f978a5840b
